export const errorCodes = {
    authConfigInvalid: "control.configInvalid",
    controlClientIdentityInvalid: "control.clientIdentityInvalid",
    controlClientIdentityRequired: "control.clientIdentityRequired",
    controlConfigLoadFailed: "control.configLoadFailed",
    controlConfigParseFailed: "control.configParseFailed",
    controlConfigValidationFailed: "control.configValidationFailed",
    coreApprovalAlreadyDecided: "core.approvalAlreadyDecided",
    coreApprovalDenied: "core.approvalDenied",
    coreApprovalExpired: "core.approvalExpired",
    coreApprovalNotFound: "core.approvalNotFound",
    coreApprovalPolicyInvalid: "core.approvalPolicyInvalid",
    coreApprovalRequired: "core.approvalRequired",
    coreInstanceBusy: "core.instanceBusy",
    coreInstanceNotReady: "core.instanceNotReady",
    coreProviderFailed: "core.providerFailed",
    coreToolSchemaUnavailable: "core.toolSchemaUnavailable",
    coreWorkerAssetUnavailable: "core.workerAssetUnavailable",
    coreWorkerHandshakeFailed: "core.workerHandshakeFailed",
    coreWorkerProvisionFailed: "core.workerProvisionFailed",
    coreWorkerRpcDisconnected: "core.workerRpcDisconnected",
    coreWorkerRpcSpawnFailed: "core.workerRpcSpawnFailed",
    coreWorkerStartFailed: "core.workerStartFailed",
    coreWorkerStatusFailed: "core.workerStatusFailed",
    coreWorkerStopFailed: "core.workerStopFailed",
    coreWorkerTargetProbeFailed: "core.workerTargetProbeFailed",
    coreWorkerTargetUnsupported: "core.workerTargetUnsupported",
    envelopeInvalid: "control.methodNotFound",
    instanceConflict: "instance.conflict",
    instanceAlreadyExists: "control.instanceAlreadyExists",
    instanceMissing: "control.instanceNotFound",
    mcpPublicAuthRequired: "mcp.publicAuthRequired",
    streamGap: "stream.gap",
    targetInvalid: "control.invalidTarget",
    toolSchemaInvalid: "core.toolSchemaUnavailable"
} as const;

export type ErrorCode = (typeof errorCodes)[keyof typeof errorCodes];
