import { useEffect, useState } from "react";
import type { ApprovalRequest, OAuthApprovalRequest } from "@portable-devshell/shared";
import type { WebStore } from "../state/WebStore.js";

type Page = "overview" | "instances" | "approvals" | "activity";
const navigation: Array<[Page, string]> = [["overview", "Overview"], ["instances", "Instances"], ["approvals", "Approvals"], ["activity", "Activity"]];
export function App({ store }: { store: WebStore }) {
    const [state, setState] = useState(store.state); const [page, setPage] = useState<Page>("overview"); const [selected, setSelected] = useState<string>();
    useEffect(() => { const unsubscribe = store.subscribe(() => setState(store.state)); void store.load(); return () => { unsubscribe(); store.close(); }; }, [store]);
    const pending = Object.values(state.approvals).flat().filter((approval) => approval.status === "pending").length + state.oauthApprovals.filter((approval) => approval.status === "pending").length;
    return <div className="app"><aside><h1>portable-devshell</h1><Nav page={page} setPage={setPage} pending={pending} /></aside><main><header className={`connection ${state.connection}`}><span>{state.connection === "online" ? "Online" : state.connection === "connecting" ? "Connecting…" : "Offline"}</span>{state.connection !== "online" && <button onClick={() => void store.reconnect()}>Reconnect</button>}</header>{state.error && <p className="error">{state.error}</p>}{page === "overview" && <Overview state={state} pending={pending} />}{page === "instances" && <Instances state={state} store={store} selected={selected} setSelected={setSelected} />}{page === "approvals" && <Approvals state={state} store={store} />}{page === "activity" && <Activity state={state} />}</main><nav className="bottom"><Nav page={page} setPage={setPage} pending={pending} /></nav></div>;
}
function Nav({ page, setPage, pending }: { page: Page; setPage(page: Page): void; pending: number }) { return <>{navigation.map(([id, label]) => <button className={page === id ? "selected" : ""} key={id} onClick={() => setPage(id)}>{label}{id === "approvals" && pending > 0 ? ` (${pending})` : ""}</button>)}</>; }
function Overview({ state, pending }: { state: WebStore["state"]; pending: number }) { const warnings = state.instances.filter((item) => item.snapshot.status === "failed" || item.snapshot.status === "stale"); return <section><h2>Overview</h2><div className="metrics"><Metric label="Service" value={state.service?.ok ? "Ready" : "Unavailable"}/><Metric label="Instances" value={String(state.service?.instanceCount ?? state.instances.length)}/><Metric label="Pending approvals" value={String(pending)}/></div><h3>Warnings</h3>{warnings.length === 0 ? <p className="empty">No current warnings.</p> : <ul>{warnings.map(({ name, snapshot }) => <li key={name}>{name}: {snapshot.lastErrorMessage ?? snapshot.status}</li>)}</ul>}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="card"><span>{label}</span><strong>{value}</strong></div>; }
function Instances({ state, store, selected, setSelected }: { state: WebStore["state"]; store: WebStore; selected?: string; setSelected(value?: string): void }) { const entry = state.instances.find(({ name }) => name === selected); return <section><h2>Instances</h2>{state.instances.length === 0 ? <p className="empty">No instances are available.</p> : <div className="instances">{state.instances.map((item) => <button className="instance card" key={item.name} onClick={() => { setSelected(item.name); void store.refreshInstance(item.name); }}><strong>{item.name}</strong><span>{item.snapshot.status} · {item.snapshot.connectionState}</span></button>)}</div>}{entry && <article className="detail"><button className="back" onClick={() => setSelected(undefined)}>Back to instances</button><h3>{entry.name}</h3><p>Runtime: {entry.snapshot.status}; daemon: {entry.snapshot.daemonState}; sequence: {entry.snapshot.lastSeq}</p><div className="actions">{entry.snapshot.status === "stopped" ? <button onClick={() => void store.start(entry.name)}>Start</button> : <button className="danger" onClick={() => void store.stop(entry.name)}>Stop</button>}</div><h4>Recent logs</h4><pre>{(state.logs[entry.name] ?? []).map((log) => `${log.at} ${log.message}`).join("\n") || "No recent logs."}</pre></article>}</section>; }
function Approvals({ state, store }: { state: WebStore["state"]; store: WebStore }) { const tools = Object.values(state.approvals).flatMap((approvals) => approvals.filter((item) => item.status === "pending")); const oauth = state.oauthApprovals.filter((item) => item.status === "pending"); return <section><h2>Approvals</h2>{tools.length + oauth.length === 0 ? <p className="empty">Nothing needs approval.</p> : <div className="approval-list">{tools.map((item) => <ToolApproval key={item.approvalId} item={item} decide={(decision) => store.decideTool(item.instance, item.approvalId, decision)} />)}{oauth.map((item) => <OAuthApproval key={item.approvalId} item={item} decide={(decision) => store.decideOAuth(item.approvalId, decision)} />)}</div>}</section>; }
function ToolApproval({ item, decide }: { item: ApprovalRequest; decide(decision: "approve" | "deny"): Promise<void> }) { return <article className="card"><h3>{item.toolName}</h3><p>{item.instance} · {item.reason}</p><details><summary>Open details</summary><p>Risk: {item.riskLevel}; expires: {item.expiresAt}</p><p>{item.inputSummary}</p></details><Decision decide={decide}/></article>; }
function OAuthApproval({ item, decide }: { item: OAuthApprovalRequest; decide(decision: "approve" | "deny"): Promise<void> }) { return <article className="card"><h3>OAuth {item.kind}</h3><p>{item.clientName} · {item.requestedScopes.join(", ") || "no scopes"}</p><details><summary>Open details</summary><p>Redirects: {item.redirectUris.join(", ") || "none"}</p><p>Resources: {item.requestedResources.join(", ") || "none"}</p></details><Decision decide={decide}/></article>; }
function Decision({ decide }: { decide(decision: "approve" | "deny"): Promise<void> }) { const act = (decision: "approve" | "deny") => { if (window.confirm(`${decision === "approve" ? "Approve" : "Deny"} this request?`)) void decide(decision); }; return <div className="actions"><button onClick={() => act("approve")}>Approve</button><button className="danger" onClick={() => act("deny")}>Deny</button></div>; }
function Activity({ state }: { state: WebStore["state"] }) { return <section><h2>Activity</h2>{state.activity.length === 0 ? <p className="empty">No recent activity.</p> : <ol className="feed">{[...state.activity].reverse().map((event) => <li key={`${event.instanceName}-${event.seq}`}><time>{event.at}</time><strong>{event.instanceName}</strong> {event.type}</li>)}</ol>}</section>; }
