export const controlMethods = {
    controlApplyConfig: "control.applyConfig",
    controlCreateInstance: "control.createInstance",
    controlDeleteInstance: "control.deleteInstance",
    controlDisableInstance: "control.disableInstance",
    controlEnableInstance: "control.enableInstance",
    controlGetConfigView: "control.getConfigView",
    controlGetInstanceCreateSchema: "control.getInstanceCreateSchema",
    controlIdentifyClient: "control.identifyClient",
    controlListInstances: "control.listInstances",
    controlPing: "control.ping",
    controlRestart: "control.restart",
    controlShutdown: "control.shutdown",
    controlStatus: "control.status",
    controlUpdateInstanceConfig: "control.updateInstanceConfig",
    controlUpdateMcpConfig: "control.updateMcpConfig",
    controlValidateConfigDraft: "control.validateConfigDraft",
    controlValidateInstanceCreateDraft: "control.validateInstanceCreateDraft",
    instanceCallTool: "instance.callTool",
    instanceDecideApproval: "instance.decideApproval",
    instanceGetApproval: "instance.getApproval",
    instanceGetSnapshot: "instance.getSnapshot",
    instanceListApprovals: "instance.listApprovals",
    instanceReadLogs: "instance.readLogs",
    instanceReadToolCalls: "instance.readToolCalls",
    instanceRefreshStatus: "instance.refreshStatus",
    instanceStart: "instance.start",
    instanceStop: "instance.stop",
    instanceSubscribe: "instance.subscribe"
} as const;

export type ControlMethod = (typeof controlMethods)[keyof typeof controlMethods];
