import { describe, expect, it, vi } from "vitest";
import { WebStore } from "../src/state/WebStore.js";

const snapshot = { name: "demo", status: "ready", connectionState: "connected", daemonState: "running", ready: true, lastSeq: 3 };
describe("WebStore", () => {
    it("reconnects and restores subscriptions from the last sequence", async () => { const subscriptions: number[] = []; const clients = fakeClients({ subscribe: async (_name: string, fromSeq: number) => { subscriptions.push(fromSeq); return { next: async () => new Promise(() => undefined), close() {} }; } }); const store = new WebStore(clients as never); await store.load(); await store.reconnect(); expect(clients.reconnect).toHaveBeenCalledOnce(); expect(subscriptions).toEqual([3, 3]); expect(store.state.connection).toBe("online"); });
    it("refreshes and resubscribes after stream.gap", async () => { let count = 0; const subscriptions: number[] = []; const clients = fakeClients({ subscribe: async (_name: string, fromSeq: number) => { subscriptions.push(fromSeq); count++; return { next: async () => count === 1 ? { kind: "gap" } : new Promise(() => undefined), close() {} }; } }); const store = new WebStore(clients as never); await store.load(); await new Promise((resolve) => setTimeout(resolve)); expect(clients.runtime.refresh).toHaveBeenCalledWith("demo"); expect(subscriptions).toEqual([3, 9]); });
});
function fakeClients(overrides: Record<string, unknown> = {}) { const runtime = { snapshot: async () => ({ snapshot, lastSeq: 3 }), refresh: vi.fn(async () => ({ snapshot: { ...snapshot, lastSeq: 9 }, lastSeq: 9 })), readLogs: async () => [], stop: async () => snapshot, start: async () => snapshot, subscribe: async () => ({ next: async () => new Promise(() => undefined), close() {} }) }; return { close() {}, reconnect: vi.fn(async () => {}), service: { status: async () => ({ ok: true, instanceCount: 1 }) }, instance: { list: async () => [{ name: "demo", mcpEnabled: true, snapshot }] }, tool: { listApprovals: async () => [], getApproval: async () => ({}), decideApproval: async () => ({}) }, mcp: { listApprovals: async () => [], decideApproval: async () => ({}) }, runtime: { ...runtime, ...(overrides.subscribe ? { subscribe: overrides.subscribe } : {}) } }; }
